name: goreleaser

on:
  push:


permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - 
        name: Generate Man and Completions
        run: |
          go run main.go completion bash > bash-completion
          go run main.go completion zsh > zsh-completion
          go run main.go completion fish > fish-completion
          mkdir man
          go run main.go gendoc --type man
          pwd
          ls
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}